version: '3'

services:
  backend:
    build:
      context: ./Backend
    restart: always
    environment:
      - FLASK_APP_PORT=8000
      - MONGO_URL=mongodb:27017 
      - PANEL_UPDATE_INTERVAL_SECONDS=600
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
    restart: always
    environment:
      - BACKEND_API_URL=http://backend:8000
    ports:
      - "4200:4200"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb



volumes:
  dbdata:
