version: '3'

services:
  backend:
    build:
      context: ./Backend
    environment:
      - FLASK_APP_PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./Frontend
    ports:
      - "4200:4200"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
