version: '3'

services:
  mongodb:
    image: mongodb-raspberrypi4-unofficial-r7.0.5:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/dbdat
      
volumes:
  dbdata:
